# Generated by Django 5.2 on 2026-10-05 19:08

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MarcoCalendario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "semestre",
                    models.CharField(
                        help_text="Semestre em que a sessão acontece, no formato YYYY.1 ou YYYY.2.",
                        max_length=6,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Informe no formato YYYY.1 ou YYYY.2.",
                                regex="^\\d{4}\\.[12]$",
                            )
                        ],
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("PROJETO_DISSERTACAO", "Projeto de dissertação"),
                            ("QUALIFICACAO", "Qualificação"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "data_limite",
                    models.DateField(
                        help_text="Data da sessão. Quem não apresentar até ela é tratado como reprovado.",
                        verbose_name="Data limite",
                    ),
                ),
                (
                    "alterado_em",
                    models.DateTimeField(auto_now=True, verbose_name="Alterado em"),
                ),
                (
                    "alterado_por",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Alterado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "marco do calendário",
                "verbose_name_plural": "calendário de marcos",
                "ordering": ["-semestre", "tipo"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("semestre", "tipo"),
                        name="marco_calendario_semestre_tipo_unico",
                    )
                ],
            },
        ),
    ]
